### ISSUE TITLE
Question: Is it possible to support ARM architecture, OS and board independent functionality?

### ISSUE THREAD

**Issue by Aukstkalnis** [jonasblixt/punchboot#10]
Hi,

I am interested in bootloader that is not OS and SOC dependant. As I can see from Readme, bootloader is for Linux system. What should be done to have something like https://github.com/wolfSSL/wolfBoot?

**Comment by jonpe960** [comment]
Hello,

It's certainly possible to boot other things than linux with PB. For example;

This "boot driver" is adapter for lk (little kernel)

https://github.com/jonpe960/punchboot/blob/master/src/boot/lk.c

It's possible and easy to boot bare metal applications. Finding a bootloader that is SOC -independent sounds like a difficult task since the bootloader must interact with the hardware at a low level.

Jonas
